import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import { Header } from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ingressos Fast',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const res = cookies().get('user');
  const user = res?.value && JSON.parse(res.value);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header user={user} />
        {children}
      </body>
    </html>
  )
}
