import type { Metadata } from 'next'
import { cookies } from 'next/headers'
import { Header } from '@/components/header'

export const metadata: Metadata = {
    title: 'Ingressos Fast',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const res = cookies().get('user');
    const user = res?.value && JSON.parse(res.value);

    return (
        <>
            <Header user={user} />
            {children}
        </>
    )
}
